### ISSUE TITLE
代码块中会多出一个空格

### ISSUE THREAD

**Issue by longyujin9** [metheno/typecho-theme-kibou-lite#2]
![tim 20170514175543](https://cloud.githubusercontent.com/assets/22745982/26032828/48604986-38cf-11e7-90e6-ac69459b6fdd.png)
![tim 20170514175639](https://cloud.githubusercontent.com/assets/22745982/26032829/486359b4-38cf-11e7-98cd-86999844fc08.png)

**Comment by metheno** [comment]
不确定这是解析问题还是引用的JS问题。
请务必要把你的博客链接发给我╭(°A°`)╮

**Comment by longyujin9** [comment]
https://joer.moe

**Comment by metheno** [comment]
新版本可能修复了这个问题，去测试一下吧。谢谢٩(˃̶͈̀௰˂̶͈́)و
